# Generated by Django 6.0.1 on 2026-04-05 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('employee', 'Employee')], default='user', max_length=20),
        ),
        migrations.CreateModel(
            name='Sell_produts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100)),
                ('product_brand', models.CharField(max_length=100)),
                ('product_model', models.CharField(max_length=100)),
                ('product_quantity', models.IntegerField()),
                ('product_description', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=100)),
                ('phone', models.PositiveIntegerField()),
                ('address', models.CharField(max_length=100)),
                ('status', models.CharField(default='pending', max_length=100)),
                ('assigned_employee_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to='backend.users')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sell_requests', to='backend.users')),
            ],
        ),
    ]
