# Generated by Django 6.0.1 on 2026-04-10 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_users_role_sell_produts'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell_produts',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('technician', 'Technician'), ('collector', 'Collector')], default='user', max_length=20),
        ),
    ]
