# Generated by Django 6.0.1 on 2026-04-16 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_sell_produts_price_alter_users_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell_produts',
            name='assigned_technitian_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_to_test', to='backend.users'),
        ),
    ]
