# Generated by Django 6.0.1 on 2026-04-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_sell_produts_assigned_technitian_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell_produts',
            name='sell_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
