# Generated by Django 6.0.1 on 2026-04-20 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_sell_produts_sell_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ewaste_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100)),
                ('product_brand', models.CharField(max_length=100)),
                ('product_model', models.CharField(max_length=100)),
                ('product_quantity', models.IntegerField()),
                ('product_description', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=100)),
                ('phone', models.PositiveIntegerField()),
                ('address', models.CharField(max_length=100)),
                ('status', models.CharField(default='pending', max_length=100)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sell_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('type', models.CharField(choices=[('sell', 'Sell'), ('buy', 'Buy')], default='buy', max_length=10)),
                ('assigned_employee_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to='backend.users')),
                ('assigned_technitian_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_to_test', to='backend.users')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sell_requests', to='backend.users')),
            ],
        ),
        migrations.DeleteModel(
            name='Sell_produts',
        ),
    ]
